service: mug-space-server

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.mug-space.io
    basePath: ''
    certificateName: '*.mug-space.io'
    stage: ${opt:stage, 'prod'}
    createRoute53Record: true
    endPointType: 'regional'
    securityPolicy: tls_1_2


package:
  patterns:
    - '!.git/**'
    - '!src/**'
    - '!node_modules/@types/**'
    - '!node_modules/serverless/**'
    - '!node_modules/serverless-*/**'

provider:
  name: aws
  # architecture: arm64
  runtime: nodejs20.x
  memorySize: 512
  timeout: 900
  environment:
    STAGE: ${opt:stage, 'prod'}
  region: ap-northeast-2
  stage: ${opt:stage, 'prod'}
  deploymentBucket:
    name: mug-space-server-lambda-${opt:stage, 'prod'}
  ecr:
    images:
      latest:
        path: ./
        # platform: linux/amd64
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:DeleteObject"
          Resource: "*"
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  api:
    image:
      # name: latest
      command:
        - dist/lambda.handler
      # entryPoint:
      #   - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

